---
version: "2.1"

services:
  graphx:
    build:
      dockerfile: Dockerfile
      context: ./packages/graphx
    environment:
      - ENVIRONMENT=DEVELOPMENT
      - APP_URL=http://localhost:8021
      - NEO_URL=bolt://neo4j:7687
      - NEO_USERNAME=neo4j
      - NEO_PASSWORD=graphx
    ports:
      - "8000:8000"
    depends_on:
      - neo4j
    entrypoint:
      - sh
      - .docker/entrypoint.sh
    volumes:
      - ./:/code
      - /code/packages/graphx/.venv

  nginx:
    build:
      context: ./.docker/nginx/
      dockerfile: Dockerfile
    volumes:
      - ./.docker/nginx/site.conf:/etc/nginx/conf.d/site.template
      - ./.docker/logs/nginx:/var/log/nginx:cached
    ports:
      - "8021:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - PROXY_HOST=graphx
      - PROXY_PORT=8000
    depends_on:
      - graphx
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"


  neo4j:
    image: neo4j:3.5.0
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/graphx
